/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kyo_jnidemo_jni_JNIDemoUtil */

#ifndef _Included_com_kyo_jnidemo_jni_JNIDemoUtil
#define _Included_com_kyo_jnidemo_jni_JNIDemoUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kyo_jnidemo_jni_JNIDemoUtil
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kyo_jnidemo_jni_JNIDemoUtil_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
